# Generated by Django 5.2.6 on 2025-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('cough', 'Cough'), ('cold', 'Cold & Flu'), ('fever', 'Fever'), ('skin', 'Skin Allergy'), ('wound', 'Wound Care')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='herbs/')),
                ('benefits', models.TextField(blank=True, help_text='List benefits separated by commas')),
                ('prescription', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
