# Generated by Django 5.2.6 on 2025-11-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_herb'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='scientific_name',
            field=models.TextField(blank=True),
        ),
    ]
