# Generated by Django 5.2.6 on 2025-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_herb_procedure_herb_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='scientific_name',
            field=models.CharField(max_length=255),
        ),
    ]
