# Generated by Django 5.2.6 on 2025-11-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_herb_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='location',
            field=models.CharField(blank=True, help_text="Municipality or area, e.g. 'Naval' or 'Almeria'", max_length=255),
        ),
    ]
