# Generated by Django 5.2.6 on 2025-11-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_herb_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
