# Generated by Django 5.2.6 on 2025-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_herb_latitude_herb_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='location',
            field=models.CharField(blank=True, help_text='Municipality or place name', max_length=255),
        ),
    ]
