# Generated by Django 5.2.6 on 2025-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_herb_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='location',
        ),
        migrations.RemoveField(
            model_name='herb',
            name='longitude',
        ),
        migrations.AddField(
            model_name='herb',
            name='locations',
            field=models.JSONField(default=list),
        ),
    ]
