# Generated by Django 5.2.5 on 2025-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_herb_latitude_remove_herb_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative to image upload - paste image URL', null=True),
        ),
    ]
