# Generated by Django 5.2.5 on 2025-11-22 23:51

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_herb_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.herb_image_path),
        ),
    ]
