# Generated by Django 5.2.5 on 2025-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_herb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data', null=True),
        ),
    ]
